# Generated by Django 5.1.1 on 2024-10-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(upload_to="movie/images/", verbose_name="书籍封面"),
        ),
    ]
